/**
 * @file      lorawan_commissioning.h
 *
 * @brief     End device commissioning parameters
 *
 * The Clear BSD License
 * Copyright Semtech Corporation 2024. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted (subject to the limitations in the disclaimer
 * below) provided that the following conditions are met:
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of the Semtech corporation nor the
 *       names of its contributors may be used to endorse or promote products
 *       derived from this software without specific prior written permission.
 *
 * NO EXPRESS OR IMPLIED LICENSES TO ANY PARTY'S PATENT RIGHTS ARE GRANTED BY
 * THIS LICENSE. THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND
 * CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT
 * NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
 * PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL SEMTECH CORPORATION BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef LORAWAN_COMMISSIONING_H
#define LORAWAN_COMMISSIONING_H

#ifdef __cplusplus
extern "C" {
#endif

/*
 * -----------------------------------------------------------------------------
 * --- DEPENDENCIES ------------------------------------------------------------
 */

/*
 * -----------------------------------------------------------------------------
 * --- PUBLIC MACROS -----------------------------------------------------------
 */

/*
 * -----------------------------------------------------------------------------
 * --- PUBLIC CONSTANTS --------------------------------------------------------
 */

/**
 * @brief Use internal credential
 * @remark By setting true the credentials defined in this document will not be used
 */
#define USE_LR11XX_CREDENTIALS false

/**
 * @brief IEEE Organizationally Unique Identifier ( OUI ) (big endian)
 * @remark This is unique to a company or organization
 */
#define IEEE_OUI 0x00, 0x00, 0x00

/**
 * @brief Device IEEE EUI (big endian)
 *
 * @remark In this application the value is automatically generated by calling
 *         lr1110_modem_get_dev_eui function
 */
#define LORAWAN_DEVICE_EUI                     \
    {                                          \
        0xd1, 0x03, 0xbd, 0x5b, 0xa0, 0x9e, 0x48, 0x18 \
    }
#define LORAWAN_DEVICE_EUI_LEN 8

/**
 * @brief App/Join server IEEE EUI (big endian)
 */
#define LORAWAN_JOIN_EUI                               \
    {                                                  \
        0x63, 0xad, 0x92, 0x5b, 0x9b, 0xbb, 0xf9, 0x02 \
    }
#define LORAWAN_JOIN_EUI_LEN 8

/**
 * @brief loRaWAN Network Key (big endian)
 */
#define LORAWAN_NWK_KEY                                                                                \
    {                                                                                                  \
        0x42, 0xcf, 0x9d, 0x26, 0x73, 0x44, 0xe1, 0xf6, 0x7d, 0xdd, 0x46, 0xa5, 0x37, 0x37, 0x4a, 0x87 \
    }
#define LORAWAN_NWK_KEY_LEN 16

/**
 * @brief loRaWAN Application Key (big endian)
 */
#define LORAWAN_APP_KEY                                                                                \
    {                                                                                              \
        0x98, 0x47, 0xBA, 0x01, 0x8E, 0x06, 0x56, 0x34, 0x9E, 0x72, 0x95, 0xE9, 0xC0, 0xF9, 0x1C, 0xA9 \
    }
#define LORAWAN_APP_KEY_LEN 16

/*
 * -----------------------------------------------------------------------------
 * --- PUBLIC TYPES ------------------------------------------------------------
 */

/*
 * -----------------------------------------------------------------------------
 * --- PUBLIC FUNCTIONS PROTOTYPES ---------------------------------------------
 */

#ifdef __cplusplus
}
#endif

#endif  // LORAWAN_COMMISSIONING_H

/* --- EOF ------------------------------------------------------------------ */
