[env:ESP32-S3-LR1121-XF]
extends = esp32s3_base
board = esp32-s3-zero
board_build.partitions = partition-table.csv
board_level = extra
board_upload.flash_size = 4MB
build_unflags =
  ${esp32s3_base.build_unflags}
build_flags =
  ${esp32s3_base.build_flags}
  -D ESP32_S3_LR1121_XF
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -I variants/esp32s3/ESP32-S3-LR1121-XF
